package Terceros;


/**
* Terceros/TerceroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Terceros.idl
* miércoles 26 de septiembre de 2018 09:14:49 PM COT
*/

public interface TerceroOperations 
{
  boolean insertarTercero (String nombres, String apellidos, String telefono);
  boolean actualizarTercero (int id, String nombres, String apellidos, String telefono);
  boolean eliminarTerceros (int id);
  String consultarTerceros (int id);
  void shoutdown ();
} // interface TerceroOperations
